language: node_js
node_js:
  - "iojs-v1.4"
  - "iojs-v1.3"
  - "iojs-v1.2"
  - "iojs-v1.1"
  - "iojs-v1.0"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.6"
  - "0.4"
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" == "0.6" ] || npm install -g npm@~1.4.6'
  - '[ "${TRAVIS_RUN_SAUCE}" != "true" ] || npm install -g grunt-cli'
script:
  - 'if [ "${TRAVIS_RUN_SAUCE}" == "true" ]; then npm run sauce ; elif [ "${TRAVIS_NODE_VERSION}" != "0.11" ] && [ "${TRAVIS_NODE_VERSION}" != "0.10" ]; then npm run test-shim && npm run test-sham ; else npm test ; fi'
# NOTE: sauce_connect is disabled, because it applies to every test and we only need it on one of them.
#  It's available inside `npm run sauce`
# addons:
#  sauce_connect: true
matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      env: TRAVIS_RUN_SAUCE=true
    - node_js: "0.12"
      env: TRAVIS_RUN_SAUCE=false
  allow_failures:
    - node_js: "iojs-v1.2"
    - node_js: "iojs-v1.1"
    - node_js: "iojs-v1.0"
    - node_js: "0.11"
    - node_js: "0.9"
    - node_js: "0.8"
    - node_js: "0.6"
    - node_js: "0.4"
    - node_js: "0.12"
      env: TRAVIS_RUN_SAUCE=true
env:
  global:
    - secure: YD4HLTE93NhSxa+64MYHhnbJ2ZkREp/HGiFGE4q+AWShqAiehtqE/K3hQUe7p0+1/2/34avhm2bz31j508ayCobm6SSUhpleJH58IK3v4LI2o9qtM+2N/MPJFOIvbziHqOM6fPluowU0k3OSdEAp4U+6S23wKSuXzcUSK8upAiM=
    - secure: k7+PgLcGJL1zyMMxZ8DSRxRrmLr5sb9i4M1kCdUvw2kRGacqoI3UhdvO2AyrAD0TAjIQoRM4dL37WsgJijhTNOu1gTb5lMUXWSQU47T7tFTvpM6OlGvQ54I7iAgv5NABZ/0gDGlQDrVdb9hQPLG1FDrMxsxcdXfgXqzqbhNsv7I=
    - SAUCE_HAS_TUNNEL=true

sudo: false

