language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
before_install:
  - 'if [ -n "${SAUCE-}" ]; then npm install -g grunt-cli; fi'
script:
  - 'if [ -n "${SAUCE-}" ]; then npm run sauce; fi'
# NOTE: sauce_connect is disabled, because it applies to every test and we only need it on one of them.
#  It's available inside `npm run sauce`
# addons:
#  sauce_connect: true
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: SAUCE=true
  allow_failures:
    - env: SAUCE=true
env:
  global:
    - secure: YD4HLTE93NhSxa+64MYHhnbJ2ZkREp/HGiFGE4q+AWShqAiehtqE/K3hQUe7p0+1/2/34avhm2bz31j508ayCobm6SSUhpleJH58IK3v4LI2o9qtM+2N/MPJFOIvbziHqOM6fPluowU0k3OSdEAp4U+6S23wKSuXzcUSK8upAiM=
    - secure: k7+PgLcGJL1zyMMxZ8DSRxRrmLr5sb9i4M1kCdUvw2kRGacqoI3UhdvO2AyrAD0TAjIQoRM4dL37WsgJijhTNOu1gTb5lMUXWSQU47T7tFTvpM6OlGvQ54I7iAgv5NABZ/0gDGlQDrVdb9hQPLG1FDrMxsxcdXfgXqzqbhNsv7I=
    - SAUCE_HAS_TUNNEL=true
